import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./ui/font";
import Header from "@/Components/Header";


export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className={`${inter.className} antialiased`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
